# Generated by Django 4.2.16 on 2024-10-20 16:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('user_role', models.CharField(choices=[('Parent', 'Parent'), ('Teacher', 'Teacher'), ('Administrator', 'Administrator'), ('Police', 'Police'), ('MCA', 'MCA')], max_length=50, verbose_name='user role')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('email_or_phone', models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email or phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='gender')),
                ('prefered_means_of_communication', models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email')], max_length=20, verbose_name='prefered means of communication')),
                ('prefered_time_from', models.TimeField(blank=True, null=True, verbose_name='prefered time from')),
                ('prefered_time_to', models.TimeField(blank=True, null=True, verbose_name='prefered time to')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if user account is active.', verbose_name='active')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
