# Generated by Django 4.2.16 on 2024-10-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='prefered_means_of_communication',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prefered_time_from',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prefered_time_to',
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_means_of_communication',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email')], default='SMS', max_length=20, verbose_name='preferred means of communication'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='preferred time from'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='preferred time to'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
    ]
