# Generated by Django 4.2.16 on 2024-10-21 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_staff_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_or_phone',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator('Enter a valid email address.', code='invalid_email'), django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.', code='invalid_phone')], verbose_name='email or phone'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='bio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='profile picture')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='location')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__last_name'],
            },
        ),
    ]
